pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo "this is build stage"
            }
        }
        stage('Test') {
            steps {
                echo "this is test stage"
            } 
        }
        stage('Deploy') { 
            steps {
                echo "this is deploy stage"
            }
        }
    }
}
