pipeline {
    agent {
  label 'DevServer'
}

    stages {
        stage('Build') 
        {
            steps {
                echo "this is build stage"
            }
            post {
            success {
                    archiveArtifacts artifacts: '**/target/*.war'
                    }
                  }
        }
        
        }
        
        }

